permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Feather Bar"
  description: |
    The Feather Bar specializes in providing your hat with the perfect feather to match your style!
  font_url: "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700|Quicksand:400,700&display=swap"
  rationales:
    typefaces.primary: |
      Open Sans was selected because it is a clean modern font. Open Sans is to be used for all body copy and majority of other text.
    typefaces.secondary: |
      Quicksand is to be used for text that stands out on the page: headings, buttons, banners, nav, etc.
    colors.primary: |
      The primary colour represents the sky and the sophistication of the brand. It is used for backgrounds, text.
    colors.secondary: |
      The secondary colour acts as a contrast to the primary colour. It is used for buttons and some text.

  colors:
    patterns:
      brand.logos: "--color-primary"
      typography.links: "--color-primary"
      icons.icons: "--color-primary"
      icons.icons-with-labels: "--color-primary"

  layouts:
    default: |
      The default layout should be used for almost every page, it includes the websites primary header and footer.
