permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Feather Bar"
  description: |
  The Feather Bar specializes in providing your hat with the perfect feather to match your style!
  font_url: "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700|Quicksand:400,700&display=swap"

  colors:
    patterns:
      brand.logos: "--color-primary"
      typography.links: "--color-primary"
