title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used on banners and primary actions.
    fields:
      - name: text
        type: string
        example: "Shop Now"
      - name: url
        type: url
        example: "/products/"

  light:
    title: "Light"
    description: |
      The light button is specifically for secondary actions. It should be used within the image section to guide the user.
    fields:
      - name: text
        type: string
        example: "Shop Now"

      - name: url
        type: url
        example: "/products/"

  ghost:
    title: "Ghost"
    description: |
      The ghost button is to be used for the least important actions. It should be used on a dark background for better visibility.
    background: "--color-primary"
    fields:
      - name: text
        type: string
        example: "Shop Now"
      - name: url
        type: url
        example: "/products/"
