title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used on banners and primary actions.
  light:
    title: "Light"
    description: |
      The light button is specifically for secondary actions. It should be used in sections.
  ghost:
    title: "Ghost"
    description: |
      The ghost button is to be used in the footer and for the least important actions.
    background: "--color-primary"
