title: "Cards and Banners"
description: |
  Cards should be used to connect the image and information while linking the user to the product or destination. Banners whould be used to draw attention and provide a call-to-action.

patterns:
  banner-small:
    title: "Small Banner"
    description: |
      The small banner should be used as a subtle way to guide the user. It is for decoration and should be used on the product list page.
    fields:
      - name: banner-small-image
        type: string
        example: "banner-small-1.jpg"

      - name: text
        type: string
        example: "Explore the Feather Bar"

  product-photo-array:
    title: "Product Photos"
    description: |
      The product photo array should be used on the product info page to provide different images of the product.
    width: 500
    fields:
      - name: product-image-1
        type: string
        example: "phoenix-1.jpg"

      - name: product-image-2
        type: string
        example: "phoenix-2.jpg"

      - name: product-image-3
        type: string
        example: "phoenix-3.jpg"

  featured-card:
    title: "Featured Card"
    description: |
      The featured card should be used in the featured section as a way to highlight the currently featured products and link the user to the product's info page.
    width: 300
    fields:
      - name: name
        type: string
        example: "Raven"

      - name: featured-image
        type: string
        example: "raven.jpg"

      - name: url
        type: url
        example: "/products/"

  product-card:
    title: "Product Card"
    description: |
      The product card should be used on product list pages to provide a view of the product, name of product, and the price.
    width: 300
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product

      - name: name
        type: string
        example: "Phoenix"

      - name: price
        type: string
        example: "$8.99"

      - name: image
        type: string
        example: "phoenix.jpg"

  banner-home:
    title: "Home Banner"
    description: |
      The home banner should be used on the home page and any other pages that require a large banner to grab attention and provide a call-to-action.
    fields:
      - name: heading
        type: string
        example: "Discover the perfect hat accessories for you"

      - name: text
        type: string
        example: "Explore the Feather Bar"

      - name: banner-image
        type: string
        example: "banner-home.jpg"

      - name: button_text
        type: string
        example: "Shop Now"
        required: false

      - name: button_url
        type: url
        example: "/products/"
        required: false
