title: "Form Inputs"
description: |
  Inputs are used to gather information. They should be used within the form on the checkout page to guide the user through the process and help them fill out any required information.

patterns:
  text-input:
    title: "Text Input"
    description: |
      The text input should be used for single lines of text that are to be entered by the user, for example names and adresses.
    fields:
      - name: label
        type: string
        example: "First Name"

      - name: id
        type: string
        example: "first-name"

      - name: error
        type: string
        example: "Please enter your first name."
      - name: error-id
        type: string
        example: "text-error"

  submit-input:
    title: "Submit Input"
    description: |
      The submit input should be used as the submit button on a form.

  radio-button:
    title: "Radio Button"
    description: |
      The radio button should be used when there are a few options but only one can be selected.
    fields:
      - name: label1
        type: string
        example: "Male"
      - name: label2
        type: string
        example: "Female"
      - name: label3
        type: string
        example: "Other"
      - name: id1
        type: string
        example: "male"
      - name: id2
        type: string
        example: "female"
      - name: id3
        type: string
        example: "other"
      - name: title
        type: string
        example: "What's your preferred gender?"

  quantity:
    title: "Number Input"
    description: |
      The number input should be used when the user has to enter in the desired quantity of a product.
    fields:
      - name: label
        type: string
        example: "Quantity"

      - name: id
        type: string
        example: "quantity"

  phone-input:
    title: "Phone Input"
    description: |
      The phone input should be used when a phone number is required.
    fields:
      - name: error
        type: string
        example: "Please enter a phone number."
      - name: label
        type: string
        example: "Enter your phone number:"
      - name: id
        type: string
        example: "phone"
      - name: error-id
        type: string
        example: "phone-error"

  password-input:
    title: "Password Input"
    description: |
      The password input should be used when a password is required.
    fields:
      - name: label
        type: string
        example: "Password"
      - name: error
        type: string
        example: "Please enter a password"
      - name: error-id
        type: string
        example: "password-error"
      - name: id
        type: string
        example: "password"

  options-input:
    title: "Dropdown Menu"
    description: |
      The dropdown menu should be used when there are many options but only one can be choosen.

  email-input:
    title: "Email Input"
    description: |
      The email input should be used when an email is required.
    fields:
      - name: label
        type: string
        example: "Email"
      - name: id
        type: string
        example: "email"
      - name: error
        type: string
        example: "Please enter an email"
      - name: error-id
        type: string
        example: "email-error"

  checkbox:
    title: "Checkbox"
    description: |
      The checkbox should be used when there are different options but multiple can be selected.

  footer-email:
    title: "Footer Email"
    description: |
      The Footer Email field should be used within the main footer of the website.

  footer-submit:
    title: "Footer Submit"
    description: |
      The Footer Submit button should be used within the main footer of the website.
